# Generated by Django 3.0.4 on 2020-04-12 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0003_auto_20200405_1959'),
        ('vehicles', '0001_initial'),
        ('customers', '0005_auto_20200401_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=25)),
                ('opendate', models.DateField()),
                ('openreading', models.DateField()),
                ('closedate', models.DateField()),
                ('closereading', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
