# Generated by Django 3.0.4 on 2020-04-12 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20200401_1242'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='closereading',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='openreading',
            field=models.CharField(max_length=8),
        ),
    ]
