# Generated by Django 3.0.4 on 2020-05-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200416_1959'),
        ('bookings', '0026_auto_20200428_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_Extended',
            fields=[
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.Booking')),
                ('amount_receivable', models.IntegerField()),
                ('amount_recived', models.IntegerField()),
                ('receivable_breakdown', models.TextField()),
                ('booking_payouts', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
    ]
