# Generated by Django 3.0.4 on 2020-05-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20200416_1959'),
        ('bookings', '0029_auto_20200504_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_extended',
            old_name='amount_recived',
            new_name='amount_received',
        ),
        migrations.RenameField(
            model_name='booking_extended',
            old_name='booking_payouts',
            new_name='booking_expenses',
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
    ]
