# Generated by Django 3.0.4 on 2020-04-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='created',
        ),
        migrations.AddField(
            model_name='driver',
            name='commercial_badge',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='driving_license',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
