# Generated by Django 3.0.4 on 2020-04-16 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_auto_20200405_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=7)),
                ('amount', models.EmailField(blank=True, default='', max_length=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
