# Generated by Django 3.0.4 on 2020-04-16 14:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_auto_20200416_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='incentive',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incentive',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
