# Generated by Django 3.0.4 on 2020-04-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_auto_20200416_2003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incentive',
        ),
    ]
