# Generated by Django 3.0.4 on 2020-04-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(max_length=10)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('owner_name', models.CharField(max_length=50)),
                ('registration_date', models.DateField()),
                ('insurance_expiry', models.DateField()),
                ('emission_expiry', models.DateField()),
                ('permit_expiry', models.DateField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
