# Generated by Django 3.0.4 on 2020-03-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200330_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-28 15:25:00'),
            preserve_default=False,
        ),
    ]
